apiVersion: v1
kind: Service
metadata:
  name: student-assistant-{{ .Values.version }}
  labels:
    app: student-assistant
    version: {{ .Values.version }}
spec:
  selector:
    app: student-assistant
    version: {{ .Values.version }}
  ports:
    - name: backend
      port: 8000
      targetPort: 8000
    - name: frontend
      port: 8501
      targetPort: 8501
